part of 'therapist.dart';

Map<String, dynamic> _$TherapistToJson(Therapist instance)=><String, dynamic>{
  'id': instance.id,
  'f_name': instance.fName,
  'l_name': instance.lName,
  'gender': instance.gender,
  'phone': instance.phone,
  'email': instance.email,
  'birth_date': instance.birthDate,
  'email_verified_at': instance.emailVerifiedAt,
  'blocked_at': instance.blockedAt,
  'avatar_url': instance.avatarUrl,
  'audio_intro': instance.audioIntro,
  'video_intro': instance.videoIntro,
  'earnings': instance.earnings?.toJson(),

  // 'video_intro': instance.videoIntro,
  // 'linkedin_url': instance.linkedinUrl,
  // 'identity_url': instance.identityUrl,
  // 'employment_status': instance.employmentStatus,
  // 'company': instance.company,
  // 'company_address': instance.companyAddress,
  // 'approved': instance.approved,
  // 'languages': instance.languages,
  // 'years': instance.years,
  // 'rating': instance.rating,
  // 'specialties': instance.specialties,
  // 'available_time': instance.availableTime,
  // 'fee': instance.fee,
  // 'bio': instance.bio,
  // 'cv_url': instance.cvUrl,
  // 'staff_id': instance.staffId,
  // 'latitude': instance.latitude,
  // 'longitude': instance.longitude,
  // 'time_zone': instance.timeZone,
  // 'location': instance.location,
  // 'timezone_identifier': instance.timezoneIdentifier,
  // 'online_status': instance.onlineStatus,
  // 'auth_token': instance.authToken,
  // 'fcm_token': instance.fcmToken,
  // 'therapist_type': instance.therapistType,
  // 'ai_prompt': instance.aiPrompt,
  // 'currency': instance.currency,
  // 'last_seen': instance.lastSeen,
  // 'bvn': instance.bvn,
  'created_at': instance.createdAt?.toIso8601String(),
  'updated_at': instance.updatedAt?.toIso8601String(),
};